# Generated by Django 4.2.11 on 2024-04-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_product_image'),
    ]

    operations = [
    ]
