# Generated by Django 4.2.11 on 2024-04-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_product_weeks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weeks',
        ),
        migrations.AddField(
            model_name='product',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
