# Generated by Django 4.2.11 on 2024-04-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_product_weeks_product_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
