# Generated by Django 4.2.11 on 2024-09-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_invoice_currency_invoice_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='zid_url',
            field=models.URLField(default=''),
        ),
    ]
