# Generated by Django 4.2.7 on 2024-04-13 17:31

from django.db import migrations, models
import django.db.models.deletion
import learning.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('duration', models.FloatField()),
                ('rating', models.FloatField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer', models.FileField(upload_to='trailers/')),
                ('random_slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingMovies',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_slug', models.CharField(default=learning.models.random_slug_generator, max_length=12, unique=True)),
                ('video', models.FileField(upload_to='videos/')),
                ('complexity', models.FloatField()),
                ('length', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='learning.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
