# Generated by Django 4.2.11 on 2024-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        
        # Add the new field 'genre' to the 'Movie' model 
         
    ]
