# Generated by Django 4.2.7 on 2024-04-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
