# Generated by Django 4.2.11 on 2024-04-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_movie_country_flag_movie_genre'),
    ]

    operations = [
        
        migrations.RunSQL(
            "ALTER TABLE learning_movie ADD COLUMN IF NOT EXISTS genre VARCHAR(100) DEFAULT '28';",
            reverse_sql="ALTER TABLE learning_movie DROP COLUMN genre;",
        ),
        
    ]
