# Generated by Django 4.2.11 on 2024-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20240423_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='iso_code',
            field=models.CharField(default='xx', max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country_flag',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
