# Generated by Django 4.2.7 on 2024-04-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_remove_movie_name_movie_backdrop_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(default='movie', max_length=10),
        ),
    ]
