# Generated by Django 4.2.7 on 2024-04-15 15:59

from django.db import migrations, models
import learning.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='random_slug',
            field=models.SlugField(default=learning.models.random_slug_generator, unique=True),
        ),
    ]
