# Generated by Django 4.2.11 on 2024-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_movie_genre'),
    ]

    operations = [
    ]
