# Generated by Django 4.2.7 on 2024-04-16 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_community_lang_trendingmovies_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingmovies',
            name='title',
        ),
        migrations.AlterField(
            model_name='trendingmovies',
            name='movie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learning.movie'),
        ),
    ]
