# Generated by Django 4.2.11 on 2024-04-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_language_iso_code_movie_country_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['date_added']},
        ),
    ]
