# Generated by Django 4.2.11 on 2024-04-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subtitle_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='transcript_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
