# Generated by Django 4.2.7 on 2024-04-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_remove_trendingmovies_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='iso_code',
            new_name='tmdb_code',
        ),
        migrations.AddField(
            model_name='language',
            name='fb_code',
            field=models.CharField(default='en_XX', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='is_src_lang',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_text', models.TextField()),
                ('is_hardest_word', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='learning.language')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='learning.video')),
            ],
        ),
    ]
