# Generated by Django 4.2.11 on 2024-04-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_movie_genre'),
    ]

    operations = [
    ]
