# Generated by Django 4.2.11 on 2024-04-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_movie_subtitle_path_movie_transcript_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
