# Generated by Django 4.2.11 on 2024-04-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='learning.movie'),
        ),
    ]
