# Generated by Django 4.2.11 on 2024-05-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_movie_movie_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
