# Generated by Django 4.2.11 on 2024-04-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_movie_genre_notification_movie'),
    ]

    operations = []
