# Generated by Django 4.2.11 on 2024-05-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_video_audio_video_thumbnail_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
