# Generated by Django 4.2.11 on 2024-04-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_movie_genre'),
    ]

    operations = [
    ]
