# Generated by Django 4.2.11 on 2024-04-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_movie_genre'),
    ]

    operations = [
    ]
