# Generated by Django 4.2.11 on 2024-04-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_movie_budget_movie_genre_movie_homepage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='backdrop_path',
        ),
    ]
