# Generated by Django 4.2.11 on 2024-04-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(default='https://www.worldatlas.com/r/w1200/upload/56/c5/7c/shutterstock-520792630.jpg', upload_to='cover_pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='https://api.dicebear.com/8.x/adventurer/svg?seed=Lucy', upload_to='profile_pictures/'),
        ),
    ]
