# Generated by Django 4.2.11 on 2024-04-25 00:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_language_iso_code_movie_country_flag'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='learning.post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='commented_by', to='learning.comment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(default=users.models.default_cover_pic, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_by', to='learning.post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_languages',
            field=models.ManyToManyField(blank=True, related_name='favourite_of', to='learning.language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='learning.post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posted_by', to='learning.post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default=users.models.default_profile_pic, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reported_by', to='users.report'),
        ),
    ]
