# Generated by Django 4.2.11 on 2024-04-25 08:12

from django.db import migrations, models
import django_countries.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_language_iso_code_movie_country_flag'),
        ('users', '0002_alter_userprofile_bookmarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=users.models.genrate_bio, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='SA', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='community',
            field=models.ManyToManyField(default=0, related_name='community_of', to='learning.community'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='favourite_movies',
            field=models.ManyToManyField(default=0, related_name='favourite_of', to='learning.movie'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='known_languages',
            field=models.ManyToManyField(default=0, related_name='known_by', to='learning.language'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='videos_watched',
            field=models.ManyToManyField(default=0, related_name='watched_by', to='learning.video'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='watched_movies',
            field=models.ManyToManyField(default=0, related_name='watched_by', to='learning.movie'),
        ),
    ]
