# Generated by Django 4.2.11 on 2024-04-21 00:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_cover_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(default='https://www.worldatlas.com/r/w1200/upload/56/c5/7c/shutterstock-520792630.jpg', upload_to=users.models.upload_to),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='https://api.dicebear.com/8.x/adventurer/svg?seed=Milo', upload_to=users.models.upload_to),
        ),
    ]
