# Generated by Django 4.2.11 on 2024-05-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_bio_alter_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='card_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
