# Generated by Django 4.2.11 on 2024-04-21 13:07

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_movie_genre'),
        ('users', '0003_alter_userprofile_cover_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='paid_user',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='posts',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarked_by', to='learning.post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comments',
            field=models.ManyToManyField(related_name='commented_by', to='learning.comment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_by', to='learning.post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='learning.post'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paid_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='posts',
            field=models.ManyToManyField(related_name='posted_by', to='learning.post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='https://api.dicebear.com/8.x/adventurer/svg?seed=Buddy', upload_to=users.models.upload_to),
        ),
    ]
