# Generated by Django 4.2.11 on 2024-04-21 14:28

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprogress_bookmarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='https://api.dicebear.com/8.x/adventurer/svg?seed=Charlie', upload_to=users.models.upload_to),
        ),
    ]
