# Generated by Django 4.2.11 on 2024-05-20 08:53

from django.db import migrations, models
import django.db.models.deletion
import string
import random

def generate_unique_referral_code(apps):
    UserProfile = apps.get_model('users', 'UserProfile')
    length = 8
    characters = string.ascii_uppercase + string.digits
    while True:
        referral_code = ''.join(random.choices(characters, k=length))
        if not UserProfile.objects.filter(referral_code=referral_code).exists():
            return referral_code

def set_unique_referral_codes(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    for profile in UserProfile.objects.all():
        if not profile.referral_code:
            profile.referral_code = generate_unique_referral_code(apps)
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='users.userprofile'),
        ),
        migrations.RunPython(set_unique_referral_codes),
        
    ]


