# Generated by Django 4.2.11 on 2024-04-21 16:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_report_video_report_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='https://api.dicebear.com/8.x/adventurer/svg?seed=Bailey', upload_to=users.models.upload_to),
        ),
    ]
