# Generated by Django 4.2.11 on 2024-09-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscriptionExpiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
