# Generated by Django 4.2.11 on 2024-04-21 16:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='https://api.dicebear.com/8.x/adventurer/svg?seed=Cooper', upload_to=users.models.upload_to),
        ),
    ]
