# Generated by Django 4.2.11 on 2024-04-22 00:49

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='Buddy', upload_to=users.models.upload_to),
        ),
    ]
