# Generated by Django 4.2.11 on 2024-04-22 04:22

from django.db import migrations, models
import django_countries.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(upload_to=users.models.upload_to),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(upload_to=users.models.upload_to),
        ),
    ]
